### ISSUE TITLE
Is it possible to attach an instance of a controller to the express app?

### ISSUE THREAD

**Issue by AlexFence** [serhiisol/node-decorators#102]
I personally don't really care much about the DI of node-decorators and would like to inject my dependencies manually like so:

```typescript
@Controller("/hello")
export class HelloController {
    private someThing: any ;

    constructor(dependency: any) {
        this.someThing = dependency;
    }

    @Get("/world")
    async create(@Res() response: Response) {
        return response.send(this.someThing.foo());
    }
}

attachControllers(app, [ new HelloController({ foo: () => ({yay: 42 })) ]);
```
If you really don't want to support such a thing, then some guidance on how I can achieve this using the DI package would be appreciated.

**Comment by AlexFence** [comment]
I quickly tried to add the support myself, its currently still sort of messy, but it appears to work
https://github.com/AlexFence/node-decorators/commit/d783e93a770f5a951fec0119e6c393a52b254d1d

The biggest Issue probably is that `attachControllerInstances` accepts an array of random objects. Maybe a controller should extends some other class or implement some kind of interface.

Anyway, I am not creating a pull request just yet. 
Looking forward to some kind of feedback at a more reasonable time of day. :sleeping:

**Comment by serhiisol** [comment]
@AlexFence just for the sake of curiosity, why don't you like dependency injection ? I found that very simple, intuitive and pretty much straight forward thing in TS development.

**Comment by AlexFence** [comment]
@serhiisol I like DI as a concept. What I don't like are all the DI frameworks/libraries/etc, I like to DI in a simple way, even if it means more code or less convenience.

I've used DI frameworks in Java and PHP before but I also have seen codebases where the framework was providing some native way to do DI and was simply ignored by the authors of the codebases, because they did not understand what it is and why you'd want to use it.

When a class specifies its dependencies via its constructor, it makes clear what you need to create and use the class and does not need any knowledge of the API or terminology of the DI Framework/System and does not require any third party code.

a silly example with *a way too complicated* Hello World Program:

```typescript
interface DisplayerInterface {
    display(text);
}

class ConsoleDisplayer implements DisplayerInterface { 
    display(text) { 
        console.log(text);
    }
}

class HelloWorld { 
    private displayer: DisplayerInterface;

    constructor(displayer: DisplayerInterface) { 
        this.displayer = displayer;
    }

    hello() {
        this.displayer.display("Hello World");
    }
}

new HelloWorld(new ConsoleDisplayer()).hello();
```

The main benefit here is that people that are not familiar with DI frameworks, (that might even get confused by many dependencies too), can easily understand what a class needs and inject the dependencies manually, after all this is what DI is at its core. Of course this may lead to layers of passing some object down the hierarchy, but this is something I am willing to do, for less infrastructure.

---
So what do think about my reasoning? Maybe I haven't considered a few things. 

I just really feel like an additional dependency is more *"Technical debt"* than actually helpful when it comes to DI.

I hope you understand where I am coming from

**Comment by serhiisol** [comment]
DI brings flexibility in general, you don't need to care about instances, DI package instantiates them for you, you don't need to deal with instantiation in general.

In general if you don't want to use DI you have two options:
1) you don't need to mark them as an `Injectable` and use deps directly in the constructor
2) make a pr, where you will be able to pass instances of the controllers.

**Comment by serhiisol** [comment]
Merged :D
