### ISSUE TITLE
Route param on controller route

### ISSUE THREAD

**Issue by chunkitmax** [serhiisol/node-decorators#104]
https://github.com/serhiisol/node-decorators/blob/69047a892fc2d93cf5da9d0a350691f7dba8d2ff/express/src/express.ts#L44

Would it be better to have a parameter for the option "mergeParams"?
```js
const router: Router = Router({ mergeParams: true }); 
```

because i found trouble to have a controller like this
```js
@Injectable()
@Controller('/:id/abc')
export default class Abc {}
```
where req.params.id === undefined on any method

**Comment by serhiisol** [comment]
Hi @chunkitmax, I can add params to the controller decorator.
