### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by alisonmoura** [serhiisol/node-decorators#105]
Hi! First of all, thanks for the work, simply amazing! I've using it on my personal projects and I am think to use it on company's projects too. But I am afraid that there is no recent updates, so I really would like to know if you guys pretend to continue this project. If you do, I'll be more than happy to contribute 😄

**Comment by serhiisol** [comment]
Hi @alisonmoura. Thanks a lot. At the moment I do adjustments to the library when it's possible. I've used it on my personal projects, but at the moment I put it on hold. I'll continue working on the project. If you have any ideas, feel free to submit PR will be much appreciated :)

**Comment by alisonmoura** [comment]
Thanks @serhiisol! I'll try to contribute with something as soon as possible. Do you have any suggestion? I don't have so much advanced knowledge on TypeScript and Nodejs for building frameworks like this, but I really like to learn, and learning by doing it's the best, in my opinion

**Comment by freemanlam** [comment]
@serhiisol, appreciated for you works.

I used this in small projects, for larger use case I'll suggest to use @nestjs. Nest provided advanced module based di and features like @angular and integrated many popular packages, but sometimes I just need a simple di, then this project is fit.

I can share one of my case: In one project I'm working on, I ned to migrate a expressjs app to nest, my solution is use `@decorators/di` and `@decorators/express` to introduce di as my first step, and write decorators `@SetMetadata`, `@UseGuards`, `@Module` and related mechanism to make the look very like nest, then I transform source code 'module by module' to a real nest project. The migrate is still not completed,  I will try to share these source code if I have time )

**Comment by serhiisol** [comment]
yeah, good idea.

**Comment by alisonmoura** [comment]
Cool!
