### ISSUE TITLE
Not finding @body

### ISSUE THREAD

**Issue by ZeroRaven23** [serhiisol/node-decorators#115]
I'm not able to find the parameters that I pass inside the Body as json in postman.

![image](https://user-images.githubusercontent.com/79873070/181819283-39a2eb69-3fcb-4f21-ac09-c5dbf88ad1e5.png)

**Comment by serhiisol** [comment]
Hi @ZeroRaven23 Thanks for the feedback, I'll take a look.

**Comment by ZeroRaven23** [comment]
`  @Post('/')
  postUser(@Body() body, @Response() res) {
    try{
    res.send(body);
  }catch(err){
    res.send(err.message)
  }}`

I did the same using body-parser, and it's returning empty

![image](https://user-images.githubusercontent.com/79873070/182155665-20f1ec19-2395-4db4-8d38-6e02dd0ecab7.png)

**Comment by serhiisol** [comment]
Do you have `body-parser` installed? If not I would suggest to do so, cause body parser gives that body property over the request.

**Comment by ZeroRaven23** [comment]
yes i have it installed

````
import { json } from "body-parser";
app.use(json())
````

**Comment by serhiisol** [comment]
well, I'm not sure where's the problem. Could you check what's inside of your `request.body` ? Is there a property `body` at all in `request`?

**Comment by ZeroRaven23** [comment]
it's giving empty, so the problem must be right here

**Comment by serhiisol** [comment]
if there's no body in request, then you have to check your application setup. Decorators just pass you `request.body` property if there's one. Otherwise it returns `request` itself.

**Comment by ZeroRaven23** [comment]
okay thanks
