### ISSUE TITLE
Unable to get sent object with @Body

### ISSUE THREAD

**Issue by ghzcool** [serhiisol/node-decorators#122]
I have this code in controller:
```
@Post('/')
postData(@Response() res, @Body() user: User) {
    console.log('post', user);
    res.send(this.userService.addUser(user));
}
```

and when I send in body:
```
{
  "firstName": "Ivan",
  "lastName": "Dudin"
}
```
with heaader content-type: application/json

in console it prints:
"post  <ref *2> IncomingMessage {
  _readableState: ReadableState {
    objectMode: false,
..."

tried to add bodyParser to app:

```
app.use(bodyParser.urlencoded({extended: false}));
app.use(bodyParser.json({type: 'application/*+json'}));
app.use(bodyParser.text({type: 'text/html'}));
```

then it prints:
"post {}"

**Comment by ghzcool** [comment]
It would be great to have some demo project where all available functionality is present. This sample project would be possible to use for testing of this lib and also to use as starting point of new project or as code samples to copy and use.

**Comment by serhiisol** [comment]
@ghzcool here's the example of decorators server https://github.com/serhiisol/decorators-server

**Comment by serhiisol** [comment]
I'm not sure, but is `application/*+json` it correct? with regular `application/json` works just fine.

**Comment by ghzcool** [comment]
changed to "application/json" and now it works. thank you
