### ISSUE TITLE
Question: example of how to use error middleware?

### ISSUE THREAD

**Issue by markkelsall** [serhiisol/node-decorators#137]
Hi,
Apologies for raising lots of issues, but have you got an example of attaching error middleware to an express app? I can see the readme example but it seems incomplete to me. Maybe I'm reading it wrong.

While I'm asking, have you got any tests to validate functionality?

Thanks
Mark

**Comment by serhiisol** [comment]
Container is a export from `@decorators/di` package that `@decorators/express` uses underneath. 
Yes error middleware gets called only when error happens. Take a look at the whole repository as a reference.

**Comment by markkelsall** [comment]
Thanks, I had a closer look at your demo repo and it makes sense that you just set up the middleware but still don't see how the server app instance knows to use it as app and Container don't know about each other? 

When pulled your decorators-server repo down, I couldn't get it to run, nor could I make error middleware trigger when I purposefully threw an error in one of my controllers.

**Comment by serhiisol** [comment]
Here's the app file - https://github.com/serhiisol/decorators-server/blob/master/src/app.ts

**Comment by markkelsall** [comment]
Ok understand how they reference each other now - https://github.com/serhiisol/node-decorators/blob/master/express/src/express.ts#L14
However, it doesn't seem to work for me:

```
@Controller("/TestDecorator")
export class TestDecoratorController {
	@Get("/:id")
	getData(@DecoratorResponse() res, @Params("id") id: string): any {
		console.log("id", id);
		throw new Error("argh");
		// res.status(200).send({
		// 	id,
		// 	message: "hello"
		// });
	}
}

class ServerErrorMiddleware implements ErrorMiddleware {
	use(error: Error, request: Request, response: Response, _next: NextFunction) {
		console.log("caught this error", error.message);
		response.status(200).json({ message: "error" });
	}
}

Container.provide([{ provide: ERROR_MIDDLEWARE, useValue: ServerErrorMiddleware }]);

attachControllers(app, [TestDecoratorController]);
```

I'm expecting the response to the browser to be a json object with the message "error" but I'm just getting the native error being thrown back

**Comment by serhiisol** [comment]
Have you provided it via `Container` and `ERROR_MIDDLEWARE` token?

**Comment by markkelsall** [comment]
Yes, based on the snippet above, that should be everything right? However the response is the error that is thrown in the controller rather than error middleware code

**Comment by serhiisol** [comment]
Hm, must be a bug. I'm going to fix it now.

**Comment by serhiisol** [comment]
awkward, There's an issue with instantiating a controller:
```const controller = await extractController(Controller);```
removing await works as expected, with it doesn't :D

**Comment by serhiisol** [comment]
what version of the `@decorators/express` do you have?

**Comment by serhiisol** [comment]
This issue must have appeared with the latest release. With async providers introduced in the latest di package error middleware is applied before handlers. I'll prepare a release in a bit.

**Comment by serhiisol** [comment]
Pushed new version.
