### ISSUE TITLE
Feature Request - Dynamic controller (class) instance

### ISSUE THREAD

**Issue by cmanrique-surtec** [serhiisol/node-decorators#139]
Add a way for controllers to be generated on request, to make it easier, for example, to lowered the boilerplate of add request/response per method

_Edit._
Currently when the application starts, it creates a unique instance of each class and uses those instances continuously.

If you could generate the instance dynamically you could do something like this:
e.g.
```ts
@Controller('/')
class SomeController{
  constructor(@Req() private req, @Res() private res) {}
  
  @Get('/some-action')
  someAction() {
    if (!req.headers.something) {
       res.sendStatus(400)
      return
    }
    return someGood
  }
  ...
}
```

**Comment by serhiisol** [comment]
@cmanrique-surtec could you add more details? I don't think I understand the problem.

**Comment by vikaskandari** [comment]
Are you talking about CLI ? like >_ nest generate controller abc

**Comment by cmanrique-surtec** [comment]
Edited

**Comment by vikaskandari** [comment]
I still don't understand what you are trying to say , as far as per the code , you want req , res in constructor  so we don't have to reference them via method arguments

**Comment by cmanrique-surtec** [comment]
Initially yes, but it can be very useful for some other scenario, where you want to generate something that is used in all the methods and has to be generated in each request

**Comment by vikaskandari** [comment]
I am not sure if its possible as Express will not know for which route it has to send the response. 

example : 
```typescript

@Controller('/')
class SomeController{
  constructor(@Req() private req, @Res() private res) {}
  
  @Get('/action/1')
  action1() {
    res.send("Action 1");
  }

 @Get('/action/2')
  action2() {
    res.send("Action 2");
  }

}

```
express will send the response of controller not method  but i think its possible but  it will be a custom logic

**Comment by cmanrique-surtec** [comment]
If this is not possible, or is too complex, dismiss the request and close it. The module is great as it is, but if this could be implemented, it would be a tool that would allow programming as if it were c# or java, it's already very close.

**Comment by cmanrique-surtec** [comment]
@serhiisol ?

**Comment by serhiisol** [comment]
Could you give a scenario where it can be useful? cause at the moment it's not possible, and I can think of the CLI to generate a controller way only.
