### ISSUE TITLE
Feature Request - attach custom decorators

### ISSUE THREAD

**Issue by vikaskandari** [serhiisol/node-decorators#141]
Is there a way to route though custom decorators in controller or its method for example 

```typescript

@Access("CAN_POST_PERMISSION") // <-- i should be able to access the request and response objects and validate the request
@Post("/")
getPost(){
  return "POST ALLOWED"
}

```

```@Access()``` is custom decorator to check if user is allowed to access the api endpoint  or is there another robust way to do this ?

**Comment by serhiisol** [comment]
I believe you can, you can wrap original function with custom and add extra logic on top, something like:


```typescript
function Access(rule: string) {
  return (target: object, key: string, descriptor: any) => {
    const handler = descriptor.value;

    descriptor.value = (...args) => {
      if (ALLOWED_RULES.includes(rule) {
        return handler.apply(target, args);
      }
      
      throw new Unauthorized();
    };

    return descriptor;
  };
}
```

**Comment by vikaskandari** [comment]
but how do i access the request and  response objects in the access decorator factory ? so i can directory send the response or use next function if rule exists

**Comment by cmanrique-surtec** [comment]
Use middleware
```ts
function Access(value) {
	return (req, res, next) => {
		// your logic
	}
}
```
```ts
@Post("/", [Access('CAN_POST_PERMISSION')])
getPost(){
  return "POST ALLOWED"
}
```

**Comment by vikaskandari** [comment]
Currently i am using middleware method but i wanted to use decorators to keep code neat , 

Currently i have two decorators in my mind 

```Validate(DtoClass)``` this decorator will take class-validator as input and validate the request and send error if validation fails 

and 

```Access("PERMISSION_NAME") ``` this will validate the request if user have permission to access this api or not

**Comment by serhiisol** [comment]
Probably there must be a customDecorator function to create a decorator. I'll take a look.
