### ISSUE TITLE
Feature request - Custom http code handling 

### ISSUE THREAD

**Issue by vikaskandari** [serhiisol/node-decorators#145]
Currently we have Status decorator for setting status code and then we either use res.send or return the value, however i would like to have a option to handle error codes as function for example :- 

```typescript
   @Get("/")
    getTest() {
       return ThrowNotFoundError("this is my message it can be an object or string");
    }
```

notice ```ThrowNotFoundError()``` function  this will return a object with a standard error object which will be common throughout the project  just like nest.js have.

 the problem here is we have to provide Response object through function args in order to set code example :-

 ```typescript
   @Get("/")
    getTest() {
       return ThrowNotFoundError(res,"this is my message it can be an object or string");
    }
```

 `ThrowNotFoundError` code will look like following :-

```typescript
export function ThrowNotFoundError(res : Response , message : string){
 //here we can do some error logs or some extra logic 
  res.status(404); 
  return {
     message : message,
     some_additional_info : "some info 1", // these can be anything but
     some_additional_info_2 : "some info 2"
  };
}
```

I do have solution for this what we can do is return some sort of signature object of express decorator form the function which will be fixed and additional params will be response body for example `ThrowNotFoundError`  will look like following:-

```typescript
export function ThrowNotFoundError(body: any){
 //here we can do some error logs or some extra logic 
  return {
      signature : "__EXPRESS_RESPONSE__",
      code : 404,
      body : {
          message : body,
          some_additional_info : "some info 1", // these can be anything but
          some_additional_info_2 : "some info 2"
     }
  }
}
```

function will  return following object which will be processed by express decorator internally :-
```javascript 
{
  signature : "__EXPRESS_RESPONSE__",
  code : 404,
  body : {
          message : body,
          some_additional_info : "some info 1", // these can be anything but
          some_additional_info_2 : "some info 2"
     }
}
```

if signature matches server will send following response with 404 status code  :-

```javascript
 {
        message : "this is my message it can be an object or string",
        some_additional_info : "some info 1", // these can be anything but
        some_additional_info_2 : "some info 2"
  }
```

`code` and `signature` is only for express decorator internal use.

when we attach routes we will check if return value from route is equal to signature  `__EXPRESS_RESPONSE__` if signature object matches then we will send custom response  from `body` with status `code` which is `404`

this way we can define some standard responses from api's so we don't have to deal with response objects again and again on each route and controller.

let me know if such thing is already implimented or it can be done better ways otherwise i will submit pull request with above update.

**Comment by vikaskandari** [comment]
Yes i tried it today

**Comment by serhiisol** [comment]
Here's the full example with handling different instances of errors:
```ts
import * as express from 'express';
import { Container } from '@decorators/di';
import { attachControllers, Controller, ERROR_MIDDLEWARE, ErrorMiddleware, Get } from '../src';

const app: express.Express = express();

class NotFoundError extends Error {}
class InternalServerError extends Error {}

@Controller('/')
class IndexController {
  @Get('/')
  index() {
    return 'Hello World'
  }

  @Get('/not-found-error')
  notFoundError() {
    throw new NotFoundError();
  }

  @Get('/internal-server-error')
  internalServerError() {
    throw new InternalServerError();
  }
}

class ServerErrorMiddleware implements ErrorMiddleware {
  use(error: Error, _: express.Request, response: express.Response, next: express.NextFunction) {
    if (error instanceof NotFoundError) {
      return response.send('Not Found Error');
    }

    if (error instanceof InternalServerError) {
      return response.send('Internal Server Error');
    }

    next(error);
  }
}

export function start() {
  Container.provide([
    { provide: ERROR_MIDDLEWARE, useClass: ServerErrorMiddleware }
  ]);

  attachControllers(app, [IndexController]);

  app.listen(3000, () => {
    console.info(`Server is running on port 3000`);
  });
}

start();
```
