### ISSUE TITLE
Error while inject property in middelwares

### ISSUE THREAD

**Issue by Solang99** [serhiisol/node-decorators#151]
I am using an authentication middleware in my code. Initially, I tried to inject a Config object into the middleware constructor using the @Inject(Config) decorator. However, I noticed that when I accessed this.config inside the middleware's use method, it did not correspond to the expected object. Instead, it contained the value of the req object.

```
export default class AuthMiddleware implements Middleware {
  constructor(@Inject(Config) private config: Config) {}

  public async use(req: Req, res: Res, next: NextFunction): Promise<Res | void> {
    console.log(this.config);
    // Some logic
    return next();
  }
}
```

But for some reason this work as expected
```

export default class AuthMiddleware implements Middleware {

  public async use(req: Req, res: Res, next: NextFunction): Promise<Res | void> {
    const config = await Container.get(Config)
    console.log(this.config);
    // Some logic
    return next();
  }
}
```

Here are the versions of the dependencies I am using:
```
    @decorators/di: 2.0.0,
    @decorators/express 2.9.3
    typescript: 4.7.4

```

**Comment by serhiisol** [comment]
Hi @Solang99, first example is missing @Injectable decorator.

**Comment by Solang99** [comment]
I'm sorry, I forgot it in the copy paste but the problem remains

**Comment by serhiisol** [comment]
Could you prepare a gist so I can take a look?

**Comment by Tom-Challenger** [comment]
Hi @serhiisol, I have this problem too. Could you add an example to the readme file on how to properly use DI for middleware?

My case

`
### // controller.ts
@Controller('/ping')
@Injectable()
export class PingController {
    constructor() {}

    @Get('*', [WebRequestCookieMiddleware, **WebRequestAuthMiddleware**])
    async ping(
      @Request() req: PrivateWebRequest,
      @Response() response: WebResponse<string>
    ) {
        console.log('isAuth!')
        return response.status(200).send('pong');
    }
}

### // middleware.ts
@Injectable()
export class **WebRequestAuthMiddleware** implements Middleware {
    constructor(@Inject(AuthConfig) private readonly **authConfig**: AuthConfig) {
    }

    async use(req: Request, res: Response, next: NextFunction): Promise<void> {
        console.log(**this.authConfig.authCookieName**); // -> undefined
        // some logic
        return next();
    }
}
`

**Comment by Tom-Challenger** [comment]
**My solution**

### // middleware.ts

```
@Injectable()
export class WebRequestAuthMiddlewareProto implements Middleware { ...


const webRequestAuthMiddlewareInst = await Container.get<WebRequestAuthMiddlewareProto>(WebRequestAuthMiddlewareProto)

export class WebRequestAuthMiddleware implements Middleware {
  async use(req: PrivateWebRequest, res: Response, next: NextFunction): Promise<void> {
    return void await webRequestAuthMiddlewareInst.use(req, res, next)
  }
}
```

**Comment by serhiisol** [comment]
I'll take a look.
