### ISSUE TITLE
Error injection

### ISSUE THREAD

**Issue by valentimarco** [serhiisol/node-decorators#153]
Hi, first of all thanks for this amazing work but i have a problem with dependence injection library: 
I created a controller that accept a TherapiesService instance in the constructor and marked as Injectable the TherapiesService class. When i try to start the app, i get the Missing ERRORMIDDLEWARE: Here start the fun, i insert the Container.provide before attatch all controllers  as you write on your [example](https://github.com/serhiisol/decorators-server) and now when trying to send a GET request, it will reject because the method GET is not define (Same for all http methods).
I will provide the code on [gist](https://gist.github.com/valentimarco/2638b81d79fff32a3b4cfa28d2bfb2c5) (The code is in a private repo)
```json
"dependencies": {
    "@decorators/di": "^2.0.0",
    "@decorators/express": "^2.9.3",
    "@decorators/express-openapi": "^1.1.2",
    "@decorators/socket": "^3.4.1"
}
```

**Comment by serhiisol** [comment]
@valentimarco could you show me the error middleware controller and the error you're receiving ?

**Comment by valentimarco** [comment]
Update: On the ErrorMiddleware, i inserted a console.log. The error that prints:
```js
TypeError: Cannot read properties of undefined (reading 'getTherapiesbyId')
    at Therapies.getTherapies (/home/marco/WebstormProjects/Microservice/src/Controllers/Therapies.ts:19:45)
    at /home/marco/WebstormProjects/Microservice/node_modules/@decorators/express/src/express.ts:88:43
    at Layer.handle [as handle_request] (/home/marco/WebstormProjects/Microservice/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/marco/WebstormProjects/Microservice/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/marco/WebstormProjects/Microservice/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/marco/WebstormProjects/Microservice/node_modules/express/lib/router/layer.js:95:5)
    at /home/marco/WebstormProjects/Microservice/node_modules/express/lib/router/index.js:284:15
    at param (/home/marco/WebstormProjects/Microservice/node_modules/express/lib/router/index.js:365:14)
    at param (/home/marco/WebstormProjects/Microservice/node_modules/express/lib/router/index.js:376:14)
    at Function.process_params (/home/marco/WebstormProjects/Microservice/node_modules/express/lib/router/index.js:421:3)

```
This is normal, because the service is undefined and this proves that DI don't work

**Comment by serhiisol** [comment]
Could you try to add `@Controller` decorator to the controller to see if it solves the problem?

**Comment by valentimarco** [comment]
no they have the decorator

**Comment by serhiisol** [comment]
https://github.com/serhiisol/decorators-server/blob/master/src/api/auth.ts#L9

**Comment by valentimarco** [comment]
they have the decorators, i didn't touch the code that i provide

**Comment by serhiisol** [comment]
I believe that the problem is related to circular dependency issue there. Basically you need to extract DB connection initialization into additional file and import it instead of `index.ts` in the `[TherapiesService.ts](https://gist.github.com/valentimarco/2638b81d79fff32a3b4cfa28d2bfb2c5#file-therapiesservice-ts)`

**Comment by serhiisol** [comment]
I pulled your dist and updated references and it seems to be working.

**Comment by valentimarco** [comment]
So you suggest to put the initialization of Db connection in a file, and then export it where i need?

**Comment by serhiisol** [comment]
In `index.ts` file you would just need to use `start connection` method or something, but in the services you would need to use `connection` object only. Also you can use `Container` to provide connection there and in the services you would need to use injection token instead to inject connection object.

**Comment by valentimarco** [comment]
i have updated the gist. The problem persist even if i create a new file with only the ```CoreDb``` instance and a method startconnection in the index.ts

**Comment by serhiisol** [comment]
[node_modules.zip](https://github.com/serhiisol/node-decorators/files/11584684/node_modules.zip)

Try this one.

**Comment by valentimarco** [comment]
ok works

**Comment by valentimarco** [comment]
Suggestion: Can you write it in docs that needs this param in the tsconfig? I see now that you added a tsconfig.example.json but this isn't enough.

**Comment by serhiisol** [comment]
That's the default parameter if you want to use decorators.

**Comment by valentimarco** [comment]
> That's the default parameter if you want to use decorators. 

 🤣 My bad
