### ISSUE TITLE
Where did the flexibility go?!

### ISSUE THREAD

**Issue by markkelsall** [serhiisol/node-decorators#159]
How come it has shifted to a new way of thinking AND overwriting the existing namespace and package name with the version reset?

It was great in a simple and pluggable way without being overly opinionated, allowing you to attachControllers easily to an already existing application.

**Comment by serhiisol** [comment]
I have received a lots of requests to introduce several features such as adapters support, scoped modules, custom decorators etc. and that's why I decided to reimplement core functionality. 

Legacy decorators still available in https://github.com/serhiisol/node-decorators/tree/legacy. I'll keep them updated if necessary.

**Comment by serhiisol** [comment]
I'll revert #157 change for now to prevent confusion atm

**Comment by markkelsall** [comment]
OK. Is it currently possible to attach controllers to an existing express application or is that yet to be done? 

Or is it only if you use the whole framework that you can use this?

Thanks

**Comment by serhiisol** [comment]
Currently the package is not yet published. Existing packages are available and can be used. They won't be discontinued for a long time for sure.

**Comment by serhiisol** [comment]
I've pushed packages back to the master branch with latest updates.

**Comment by serhiisol** [comment]
Closing for now, feel free to reopen if necessary

**Comment by markkelsall** [comment]
When you say the server package is not yet published, do you mean this is where attachControllers will be? I saw the change you just did, that doesn't have attachControllers in it does it?

**Comment by serhiisol** [comment]
No, `attachControllers` live in `@decorators/express` package (express folder). And I've developed new package in the server folder (presumably it's going to be `@decorators/server` package). So it won't break any existing applications that use old packages (express, socket etc.)

**Comment by markkelsall** [comment]
So will `attachControllers`, adding `@Decorator`, `errorHandlingMiddleware` be available long term to add to a separate express application? Or do you plan to remove it so it only works via `@decorators/server`

**Comment by serhiisol** [comment]
Existing packages will live as is.
