### ISSUE TITLE
HttpModule is not exported

### ISSUE THREAD

**Issue by Just-Niko** [serhiisol/node-decorators#167]
The package @decorators/server is not available on npm.

**Comment by serhiisol** [comment]
It's not yet published. I'm finilizing swagger module and then will release it.

**Comment by Just-Niko** [comment]
Thank you for the info. Is there any ETA for when it will be released?

**Comment by serhiisol** [comment]
I think by the end of this week (Friday-Saturday). It's probably going to be beta release first. I also planned to add fastify adapter as well.

**Comment by serhiisol** [comment]
@Just-Niko Just published [1.0.0-beta.1](https://github.com/serhiisol/node-decorators/releases/tag/server-1.0.0-beta.1) version, have fun.

**Comment by Just-Niko** [comment]
@serhiisol I see that the HttpModule is not exported from the package.

```typescript
import { HttpModule } from '@decorators/server'
```

 I tried importing it like that, but it can't find the module.
```typescript
import { HttpModule } from '@decorators/server/lib/platforms/http/http.module'
```

**Comment by serhiisol** [comment]
Ah, I must have forgotten to update readme. Basically it's not exported form @decorators/server package directly, but form @decorators/server/http instead.

**Comment by Just-Niko** [comment]
Importing from @decorators/server/http still shows Cannot find module or its corresponding type declarations.

**Comment by serhiisol** [comment]
Could you show me what's your npm and node versions?

**Comment by Just-Niko** [comment]
npm: 9.8.1
node: 18.17.0

**Comment by serhiisol** [comment]
Hm, I just checked an example app and it looks good. Could you try this setup:
[server-example.zip](https://github.com/serhiisol/node-decorators/files/12198612/server-example.zip)

This is an example app from example folder with package.json and update tsconfig.

**Comment by serhiisol** [comment]
I've used node 19.6.0 and npm 9.4.0.

**Comment by Just-Niko** [comment]
I get the same error with the example app.

**Comment by Just-Niko** [comment]
I added a screenshot in my previous reply. This is the only error.

**Comment by serhiisol** [comment]
Give me a sec, I see what's up

**Comment by Just-Niko** [comment]
I added "./http": "./lib/platforms/http/index.js" inside @decorators/server's package.json exports and it's now recognized. So I guess it's just a missing export.

**Comment by serhiisol** [comment]
yep, typeVersions were missing.

**Comment by serhiisol** [comment]
Could you try `beta.3` version?

**Comment by Just-Niko** [comment]
It works correctly now.

**Comment by serhiisol** [comment]
Great. I'll update the repo

**Comment by serhiisol** [comment]
@Just-Niko feel free to send me a message if you're interested in the package :)
