### ISSUE TITLE
express-session is causing ERR_HTTP_HEADERS_SENT

### ISSUE THREAD

**Issue by Just-Niko** [serhiisol/node-decorators#173]
On login, the cookie is set via an API endpoint and I redirect to /dashboard on successful login. When I use `res.render()` for the dashboard route and pass the parameters, I get the **ERR_HTTP_HEADERS_SENT**. After investigation I saw that express-session calls it's internal `res.end()` twice and then the original `res.end()` in express is called too by the `res.render()` which I believe is causing the issue.

In the bootstrap function I inject the ExpressAdapter and use `adapter.app.use(session());` to configure the middleware.

This only happens if the cookie is not set. After the first login (cookie is initially set here) when I get the **ERR_HTTP_HEADERS_SENT**, if I restart the server and refresh the page I get access to the dashboard. If I logout, don't remove the cookie and login again the dashboard loads fine.

I tried switching to @Render() and returning an object, but I got another issue there #175 . Also with that issue I have this issue as well #174 .

**Comment by Just-Niko** [comment]
I'm currently injecting both the module and the adapter because of the experiments.

**Comment by serhiisol** [comment]
Could you upload an example so I can see the whole flow?

**Comment by Just-Niko** [comment]
Unfortuantely, I can't. I can only provide general information,

**Comment by serhiisol** [comment]
@Just-Niko please try version beta.4 if it resolves your issues

**Comment by nikolays02** [comment]
It works partially with `@Render()` now, but the custom decorator I have `@CurrentUser()` returns undefined for some properties. I tried with `@Req()` directly on the controller and it works.

```typescript
export function Req() {
  return createParamDecorator((context) => {
    return (context as HttpContext).getRequest<Request>()
  })
}
```

```typescript
export function CurrentUser() {
  return createParamDecorator((context) => {
    const req = (context as HttpContext).getRequest<Request>()
    const { jwt, organization } = req.session

    return { jwt, organization, userId: jwt?.idTokenPayload?.['cognito:username'] }
  })
}
```

```typescript
@Controller()
@Pipe(AuthPipe)
export class DashboardController {
  @Get('/')
  @Render('dashboard')
  dashboard(@CurrentUser() user: User, @Req() req: Request) {
    console.log(user.organization) // returns undefined
    console.log(req.session.organization) // returns the organization data
    return {
      user
    }
  }
}
```

Unfortunately with `res.render()` I still get ERR_HTTP_HEADERS_SENT.

**Comment by Just-Niko** [comment]
It works partially with `@Render()` now, but the custom decorator I have `@CurrentUser()` returns undefined for some properties. I tried with `@Req()` directly on the controller and it works.

```typescript
export function Req() {
  return createParamDecorator((context) => {
    return (context as HttpContext).getRequest<Request>()
  })
}
```

```typescript
export function CurrentUser() {
  return createParamDecorator((context) => {
    const req = (context as HttpContext).getRequest<Request>()
    const { jwt, organization } = req.session

    return { jwt, organization, userId: jwt?.idTokenPayload?.['cognito:username'] }
  })
}
```

```typescript
@Controller()
@Pipe(AuthPipe)
export class DashboardController {
  @Get('/')
  @Render('dashboard')
  dashboard(@CurrentUser() user: User, @Req() req: Request) {
    console.log(user.organization) // returns undefined
    console.log(req.session.organization) // returns the organization data
    return {
      user
    }
  }
}
```

Unfortunately with `res.render()` I still get ERR_HTTP_HEADERS_SENT.

**Comment by serhiisol** [comment]
Do you have @Render and res.render at the same time?

**Comment by Just-Niko** [comment]
@serhiisol No as it's shown in the code. I switch between them for testing like that:

```typescript
@Controller()
@Pipe(AuthPipe)
export class DashboardController {
  @Get('/')
  dashboard(@CurrentUser() user: User, @Req() req: Request, @Res() res: Response) {
    console.log(user.organization) // returns undefined
    console.log(req.session.organization) // returns the organization data
    return res.render('dashboard', {
      user
    })
  }
}
```

**Comment by serhiisol** [comment]
I've tried to update example app with session and custom render method, I don't see any problems:

```ts
import { Application } from '@server';
import { HttpModule } from '@server/http';
import { json } from 'body-parser';
import * as session from 'express-session';
import { join } from 'path';

import { AppModule } from './app.module';

async function bootstrap() {
  const app = await Application.create(AppModule);
  const module = await app.inject<HttpModule>(HttpModule);

  module.set('view engine', 'ejs');
  module.set('views', join(__dirname, 'views'));
  module.use(json());
  module.use(session({
    secret: 'keyboard cat',
  }));

  await module.listen(3000);
  console.info('Server is running on port 3000');
}

bootstrap().catch(console.error);
```

```ts
import { Controller, Pipe } from '@server';
import { Body, Get, Params, Post, Response } from '@server/http';
import { IsString } from 'class-validator';

import { PostsService } from '../../services';
import { Access, AccessParam } from './decorators';
import { AccessPipe } from './pipes';

class PostType {
  @IsString()
  title: string;
}

@Controller()
export class PostsController {
  constructor(private postsService: PostsService) { }

  @Post('', 200)
  create(@Body() post: PostType) {
    const list = this.postsService.getPosts();

    return [...list, post];
  }

  @Access('granted')
  @Pipe(AccessPipe)
  @Get(':id', 200)
  // @Render('post')
  post(
    @Params('id') id: string,
    @AccessParam() access: string,
    @Response() res,
  ) {
    return res.render('post', { access, id });
    // return { access, id };
  }
}
```

**Comment by Just-Niko** [comment]
Hmm, I still getting undefined properties (with @Render()) for the `@CurrentUser()`. I did some console logging and here's the result:

```typescript
export function CurrentUser() {
  return createParamDecorator((context) => {
    console.log('[CurrentUser] start')
    const req = (context as HttpContext).getRequest<Request>()
    const { jwt, organization } = req.session
    console.log('[CurrentUser] end', organization)
    return { jwt, organization, userId: jwt?.idTokenPayload?.['cognito:username'] }
  })
}
```

```
[CurrentUser] start
[CurrentUser] end undefined
[CurrentUser] start
[CurrentUser] end undefined
[AuthPipe] return handle()
[Dashboard] user.organization undefined
[Dashboard] req.session.organization Organization { /* the data for is here */ }
```

Without @Render() and res.render I still get ERR_HTTP_HEADERS_SENT.

**Comment by serhiisol** [comment]
There's no magic with the `res` and the `req` objects. Param extraction happens in the route handler, basically something like:
```ts
app.get('/endpoint', (req, res) => {
  const params = extractParams(metadata, req, res);

  return actualRouteHandler(...params);
});
```

If it's not there then you might have session misconfigured.

**Comment by Just-Niko** [comment]
That's really strange. On the legacy version it was working, and now it doesn't. I'll continue investigating tomorrow.

**Comment by serhiisol** [comment]
With this decorator:
https://github.com/serhiisol/node-decorators/blob/735821574898d011662e68776891de662334e313/server/example/modules/posts/decorators/access-param.ts#L7-L11

and this route
https://github.com/serhiisol/node-decorators/blob/735821574898d011662e68776891de662334e313/server/example/modules/posts/posts.controller.ts#L30-L36
I receive the user object and rendering goes well. Also tried res.render + session middleware.

**Comment by Just-Niko** [comment]
I added a check in the AuthPipe right before return handle() and it's not throwing. So it looks like it's lost somehow.

```typescript
if (!req.session.organization) {
    throw new InternalServerError()
}
```

**Comment by serhiisol** [comment]
Btw, pipes mechanism also doesn't modify params. It could be that one of your pipes modifies request. Pipe execution order is:
Global Pipe -> controller pipe - method pipe -> route handler -> method pipe -> controller pipe -> global pipe.

**Comment by Just-Niko** [comment]
Yes the AuthPipe is modifying the request.

**Comment by Just-Niko** [comment]
Now I also see the ERR_HTTP_HEADERS_SENT when I try to render an error page.

```typescript
@Injectable()
export class ServerPipe<T> implements ProcessPipe {
  async run(context: HttpContext, handle: PipeHandle<T>) {
    const req = context.getRequest<Request>()
    const res = context.getResponse<Response>()

    try {
      return await handle()
    } catch (error) {
      console.error(error)
      const e = <ApiError>error

      if (req.path.startsWith('/api')) {
        return res.status(e.status).json({
          error: res.__(`errors.${e.status}`)
        })
      }

      return res.status(e.status).render(`error/${e.status}.ejs`)
    }
  }
}
```

**Comment by serhiisol** [comment]
It feels like you really have misconfigured server. Something either outside `@decorators/server` package sends answers before even `@decorators/server` lifecycle is finished or handler/pipe responds.
Try configuring example app I provided https://github.com/serhiisol/decorators-server-example
It's hard for me to tell where's the problem
