### ISSUE TITLE
Decorator error handling

### ISSUE THREAD

**Issue by Just-Niko** [serhiisol/node-decorators#174]
Currently if a custom decorator throws and error it looks impossible to catch it, because it's handled inside the code. The same thing applies for the @Render decorator.

https://github.com/serhiisol/node-decorators/blob/709aa174ab778a51f7e9b4b6735a4b3fe516fa97/server/src/platforms/http/helpers/route-handler.ts#L55-L57

**Comment by serhiisol** [comment]
@Just-Niko please try version beta.4 if it resolves your issues?
