### ISSUE TITLE
Missing data, EJS, express-ejs-layouts

### ISSUE THREAD

**Issue by Just-Niko** [serhiisol/node-decorators#175]
When rendering a view with `@Render` the rendering happens twice for a single request and it's missing data from `req.session`.

### First render
- The returned object from the controller is undefined (see the code below)
- An error is thrown **"Failed to lookup view "layout" in views directory "/path/to/views"**

### Second render immediately after the first one
- The returned object from the controller is available
- The data which is retrieved via a custom decorator from `req.session` is missing (but _console logging_ the `req.session` object in the `Pipe` shows the data)
- Because of the missing data in the returned object, an error is thrown for the EJS template **"Cannot read properties of undefined"**

https://github.com/serhiisol/node-decorators/blob/709aa174ab778a51f7e9b4b6735a4b3fe516fa97/server/src/platforms/http/helpers/route-handler.ts#L52-L54

**Comment by serhiisol** [comment]
@Just-Niko please try version beta.4 if it resolves your issues
