### ISSUE TITLE
Param validation

### ISSUE THREAD

**Issue by Just-Niko** [serhiisol/node-decorators#183]
On the controller method I have `@Query('q') query: string | undefined`. When going to `/items` I get:
```json
{
    "message": "Invalid param “query”. “Object” expected, “undefined” received"
}
```

If I go to `/items?q=` I get:
```json
{
    "message": "Invalid param “query”. “Object” expected, “number” received"
}
```

Even manually proving a `/items?q=test` results in:
```json
{
    "message": "Invalid param “query”. “Object” expected, “string” received"
}
```

**Comment by serhiisol** [comment]
With example app for `@Query('q') q: string | undefined` I receive the following:
```json
{
    "message": "Invalid param “q”. “String” expected, “undefined” received"
}
```

Could you show your tsconfig.json?

**Comment by Just-Niko** [comment]
```json
{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "baseUrl": ".",
    "emitDecoratorMetadata": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "importsNotUsedAsValues": "error",
    "lib": ["ESNext", "DOM"],
    "module": "CommonJS",
    "moduleResolution": "Node16",
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "outDir": "./dist",
    "removeComments": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strict": true,
    "target": "ESNext",
    "useDefineForClassFields": true,
    "strictPropertyInitialization": false
  },
  "include": ["src/*.ts", "src/**/*.ts"],
  "ts-node": {
    "files": true
  }
}
```

**Comment by serhiisol** [comment]
With your setup I managed to get expected result:
```json
{
    "message": "Invalid param “q”. “String” expected, “undefined” received"
}
```

The only thing I've changed is `strict: false` and `noImplicitAny: false`

**Comment by Just-Niko** [comment]
It should be allowed for the query params to be undefined when loading the page instead of throwing an error.

**Comment by serhiisol** [comment]
Agree, I thought `Object` was the problem. I wonder if there's a way to detect "optionals". TS returns `String` for combination of `string | undefined`.

**Comment by Just-Niko** [comment]
NestJS has a good implementation for parameter validation.

**Comment by serhiisol** [comment]
It uses class-validator under the hood as well. I've added also validation of standard types. But it feels like it won't work for complex scenarios such as `string | undefined` or `Promise<string ....>`.

**Comment by Just-Niko** [comment]
It could work if the validation function stops throwing on undefined

**Comment by Just-Niko** [comment]
```typescript
const qValidator = (q) => typeof q === string || q === undefined;
...
@Query('q', qValidator) query: string | undefined,
```

This is a good option since it's more flexible.

**Comment by serhiisol** [comment]
I think these options will be supported:

* `@Body() user: User` - if User is a class and has metadata (for class-validator)
* `@Query('q', Type) query: string | undefined` - Type can be both standard and custom (for class-validator)
* `@Query('q', validatorFunction) query: string | undefined` - for very custom-like validation

**Comment by Just-Niko** [comment]
Looks good. The issue still remains for `@Params()`. Currently I have `@Get('/:id/:subpage?')` and I get the same error because of the validation, so it should be considered too.

**Comment by serhiisol** [comment]
Yup, that's the same mechanism.
