### ISSUE TITLE
New Decorators

### ISSUE THREAD

**Issue by serhiisol** [serhiisol/node-decorators#22]
New possible Decorators:

1. Redis - https://github.com/NodeRedis/node_redis
2. JugglingDB - https://github.com/1602/jugglingdb/
3. Waterline - https://github.com/balderdashy/waterline

TBD

**Comment by AlexPikalov** [comment]
I found useful for myself to use checkboxes to track a progress of tasks that consist of few subtasks. Like

- [x] sub-task a
- [ ] sub-task b
