### ISSUE TITLE
@decorators/mongoose - @Model doesn't work with options

### ISSUE THREAD

**Issue by leodinas-hao** [serhiisol/node-decorators#44]
Firstly, Thanks for sharing this brilliant idea & your efforts putting this together. 

After spent whole afternoon today, I could't get options provided in `@Model` work in the generated mongoose schema. It seems to me that `@Model` decorator doesn't work properly at the moment when setting `SchemaTypeOpts`. What I assume is because the following reasons:

1. `SchemaTypeOpts` has not been properly parsed into `meta.options`.  Please look into the following line from `decorators/model.ts`
```
mongooseMeta.options.push(key, options[key]);
# suggest to replace with following
mongooseMeta.options.push([key, options[key]]);
```

2. Incorrect value/option being used in `buildSchema` function for setting schema options. Refer to the following in `mongoose.ts`
```
meta.options.forEach((option: string) => {
  schema.set(option, classInstance[option]);
});
# suggest to replace with following
meta.options.forEach(([name, opt]: [string, any]) => {
  schema.set(name, opt);
});
```
Thanks for your anticipated help on this.

**Comment by leodinas-hao** [comment]
Please find submitted PR #45 for this. Thanks.

**Comment by serhiisol** [comment]
HI @leodinas-hao, good job, thanks for your contribution, your PR looks good, so I'll merge it. Keep it up :D

**Comment by serhiisol** [comment]
Closing issue due to merged PR
