### ISSUE TITLE
Fix mongoose README example

### ISSUE THREAD

**Issue by bubulemaster** [serhiisol/node-decorators#46]
Hello,

in readme of mongoose, you see here :
```javascript
export let TestModel = model(TestModelClass);
```

I think it's mistake. This should be :
```javascript
export let AnimalModel = Animal.model(Animal);
```
and you not specify how import `AbstractModel` form `node-decorators/playground/mongoose/abstract.model.ts`:

```javascript
import AbstractModel from ???? 
```

Regards,

**Comment by serhiisol** [comment]
Hi @bubulemaster,

``Readme`` is correct, ``@decorators/mongoose`` packages exports helper function ``model``` which generates actual ``mongoose`` model, by extracting metadata from the class and applying it properly in ``mongoose way``.

If you'll take a look at the ``playground/mongoose``, you can find ``AbstractModel``, it's part of the playground, example of  how to create the AbstractModel you can find in ``Readme`` as well

**Comment by bubulemaster** [comment]
Ok thanks you.

Sorry for disturb.

**Comment by serhiisol** [comment]
No problem 👍
