### ISSUE TITLE
Question, __meta__ is missing error? what?

### ISSUE THREAD

**Issue by BruceHem** [serhiisol/node-decorators#50]
[ts]
Argument of type '(typeof TodosController)[]' is not assignable to parameter of type '(Injectable | ExpressClass)[]'.
  Type 'typeof TodosController' is not assignable to type 'Injectable | ExpressClass'.
    Type 'typeof TodosController' is not assignable to type 'ExpressClass'.
      Property '__meta__' is missing in type 'typeof TodosController'.

just followed docs

**Comment by serhiisol** [comment]
Hi BruceHem, thanks for the issue, I'll take a look

**Comment by BruceHem** [comment]
<img width="507" alt="screen shot 2017-09-19 at 6 18 59 pm" src="https://user-images.githubusercontent.com/15667259/30590010-1253f9f8-9d67-11e7-8403-7ffd5d1fb492.png">

and I use it like so...

<img width="454" alt="screen shot 2017-09-19 at 6 19 46 pm" src="https://user-images.githubusercontent.com/15667259/30590038-2ea50886-9d67-11e7-9836-3442887d637e.png">

**Comment by serhiisol** [comment]
@BruceHem try @decorators/express1.3.1 version
