### ISSUE TITLE
@connection an @disconnect - pass a connected or disconnected socket instance

### ISSUE THREAD

**Issue by kalu111** [serhiisol/node-decorators#53]
`
@Controller('/')
class Controller {

    @Connection()
    public async onConnection(@Socket socket: SocketIO.Socket) {
        console.log('Connected' + socket.id);
    }

    @Disconnect()
    public async onDisconnect(@Socket socket: SocketIO.Socket) {
        console.log('Disconnected' + socket.id);
    }
}
`

socket.id return "null".
It always return  Socket Server instance.
I'm wrong?

**Comment by serhiisol** [comment]
You forgot parentheses `@Socket()`

**Comment by kalu111** [comment]
Yes, thanks for that.
But it works only for @Disconnect.
On @Connection I got: _TypeError: Cannot read property 'id' of null_

**Comment by serhiisol** [comment]
Ok, I've tested it, seems to be a bug. Will add a fix shortly

**Comment by serhiisol** [comment]
@kalu111 you can try fix from https://github.com/serhiisol/node-decorators/tree/socket-2.0.1-connection-socket-fix, I'll prepare PR a bit later

**Comment by kalu111** [comment]
Thanks, I will wait for PR :)
