### ISSUE TITLE
Auto dependency injection

### ISSUE THREAD

**Issue by kalu111** [serhiisol/node-decorators#54]
Nice to have inject dependencies to Controllers by using external decorators.
For example:

```
@Injectable()
class MyService {

}

@Controller('/')
@Injectable()
class Controller {
  constructor(@Inject() myService: MyService) {}
}
```

**Comment by serhiisol** [comment]
@kalu111 I thought about this, will be added in one of the upcoming PRs :D

**Comment by serhiisol** [comment]
good news, @kalu111 , almost finished DI Container library, which I will add into socket and express decorators

**Comment by kalu111** [comment]
Good job !
