### ISSUE TITLE
Mongoose pre-save

### ISSUE THREAD

**Issue by Christilut** [serhiisol/node-decorators#58]
Thanks for this project, solves my main issue with the mongoose/typescript combination.

Just wondering how I can add a pre-save hook, I can't get it to work like this and I'm not sure how else to do it:

```ts
export type UserType = UserClass & mongoose.Document
export type UserModel = mongoose.Model<UserType>

export const User = model<UserType>({ provide: UserClass })
export const UserSchema = schema({ provide: UserClass })

UserSchema.pre('save', async function (next) {

})
```

**Comment by serhiisol** [comment]
Hi @Christilut thanks for the ticket, I think this solution should work already, cause `schema` helper function returns plain `mongoose schema object`: https://github.com/serhiisol/node-decorators/blob/master/mongoose/src/mongoose.ts#L106. But I'll test it for sure later today.

**Comment by serhiisol** [comment]
@Christilut hi, check out new PR with new hooks support and more :)

**Comment by Christilut** [comment]
Thanks, great work :)

**Comment by serhiisol** [comment]
@Christilut I'll merge it tonight
