### ISSUE TITLE
Incompatible types maybe?

### ISSUE THREAD

**Issue by BruceHem** [serhiisol/node-decorators#67]
![screen shot 2017-11-22 at 12 01 07 pm](https://user-images.githubusercontent.com/15667259/33110797-07d9f228-cf7d-11e7-80f7-2e92778f4f40.png)

**Comment by serhiisol** [comment]
Hi @BruceHem, latest typescript has more strict type check, so I confirm this issue and already working on a fix. Thanks for an issue.
