### ISSUE TITLE
DI throws error even though I'm not using it. 

### ISSUE THREAD

**Issue by BruceHem** [serhiisol/node-decorators#70]
Here is a simple controller.

![screen shot 2017-11-29 at 9 06 08 am](https://user-images.githubusercontent.com/15667259/33354261-9453703c-d4e4-11e7-9158-e3153e018128.png)

I attach this controller.
![screen shot 2017-11-29 at 9 06 46 am](https://user-images.githubusercontent.com/15667259/33354278-a90bf512-d4e4-11e7-9f06-90e83c1838cb.png)

Then ran It throws the following.
![screen shot 2017-11-29 at 9 07 24 am](https://user-images.githubusercontent.com/15667259/33354290-beeb2920-d4e4-11e7-9c16-b3688589f7ee.png)

I think we shouldn't require Injectable DI by default.

**Comment by BruceHem** [comment]
Adding Injectable decorator fixes this issue.
![screen shot 2017-11-29 at 9 11 13 am](https://user-images.githubusercontent.com/15667259/33354388-4fdd459e-d4e5-11e7-805c-200b97a8653b.png)

**Comment by serhiisol** [comment]
Yes, that's true, we can just simply fix documentation by adding injectable or we can make it as an option, but in order to use DI you have to use then injectable

**Comment by BruceHem** [comment]
I think option would be a better choice.

**Comment by serhiisol** [comment]
Well, I was thinking about this issue and came to a conclusion that simply adding `@Injectable` should be a right solution in this case. Having `@Injectable` for a controller gives you access to DI feature to your codebase. In addition, you can't use `ErrorMiddleware` cause it can be registered only via DI container and `ERROR_MIDDLEWARE` injection token.

I can add this option to a controller, so controller doesn't require `@Injectable` to be added, but `ERROR_MIDDLEWARE` still will use `DI` and `Container` in particular.

**Comment by serhiisol** [comment]
There's new update with this feature, 2.2.0
