### ISSUE TITLE
Create Injectable from object not class

### ISSUE THREAD

**Issue by pawelszczerbicki** [serhiisol/node-decorators#73]
It is possible to create injectable object without decorating a class ? I want to inject RestClient that is installed using NPM.
I want to do something like this

`Container.register(RestClient, new RestClient("http://example.com"))`
and then

`
@Injectable()
export class SomeDao(){
  constructor(private restClient: RestClient){}
}
`

**Comment by serhiisol** [comment]
Hi @pawelszczerbicki , sure, via `InjectionToken`, check out `@decorators/di` package for details. https://github.com/serhiisol/node-decorators/tree/master/di

**Comment by pawelszczerbicki** [comment]
Yes, I checked but i can not make it running. I created something like this
`Container.provide([{provide: RestClient, useValue: new RestClient("node", "http://localhost:3000")}])`
but it's not working. 
And in your example where did you get `TEST_STRING` from ? It is an import or just text ?

**Comment by serhiisol** [comment]
You have to use `InjectionToken` for it, not third party class, cause class doesn't have at that moment meta information for DI. e.g.:
```typescript
const REST_CLIENT = new InjectionToken('RestClient');
...
Container.provide([
  { provide: REST_CLIENT, useValue: new RestClient('node', 'http://localhost:3000') }
]);
...
constructor(@Inject(REST_CLIENT) private restClient: RestClient){}
...
```

**Comment by pawelszczerbicki** [comment]
Great ! Seems to work. Good job -  Thanks :)

**Comment by serhiisol** [comment]
Thanks :) Nice, I'm glad that it worked for you 👍

**Comment by pawelszczerbicki** [comment]
Just for future releases:
Maybe it is good idea to inject it via name without creating `InjectionToken`
You can create map with `objectName -> objectToInject` or `objectType -> objectToInject` and try to inject it by class name or type, or even both :)

**Comment by serhiisol** [comment]
well, I think you can use even just a string as token, but I'll definitely think about your suggestion, Thanks 👍
