### ISSUE TITLE
socket: Global Middleware is not a constructor

### ISSUE THREAD

**Issue by pawelszczerbicki** [serhiisol/node-decorators#75]
Hello
When I'm using your quick example from socket decorators I'm getting an error:

<pre><code>/node_modules/@decorators/socket/src/middleware.js:23
            instance = new middleware();
                       ^

TypeError: middleware is not a constructor
</pre></code>
How to deal with it ?
What is more, when there is no `@Injectable()` above controller, I'm getting:
<pre><code>
/node_modules/@decorators/di/src/container.js:33
            throw new errors_1.MissingProviderError(injectable);
            ^

MissingProviderError: 
        In order to get DI working, you have to provide Injectable.
        DI attempt for MessageController.
</pre></code>

**Comment by serhiisol** [comment]
middleware must be a class

**Comment by pawelszczerbicki** [comment]
I just copied your quick example from https://github.com/serhiisol/node-decorators/tree/master/socket
Would you mind to update it ? :)

**Comment by serhiisol** [comment]
Oh, my fault, will do. I’ll upload it tomorrow

**Comment by pawelszczerbicki** [comment]
Great, Thanks ! 
Why it is mandatory to provide Middleware class to container ? My middleware looks like this and it is totally useless
<pre><code>class ServerMiddleware implements Middleware {

    public use(io, socket, next) {
        next();
    }
}
</pre></code>

**Comment by luchillo17** [comment]
I want this open again under 2 things, why is the global middleware mandatory if it's empty? and if it is mandatory (i would get errors if i don't provide the global one) why the minimal example in the docs don't have it in there (i wasted hours checking issues until i found this one, and even then couldn't understand what @pawelszczerbicki was talking about)?

So i would suggest either make the global middleware have a default one in DI, or add the required Global Middleware to the minimal example of the docs.

Also i like this project a lot, should consider a [buymeacoffee](https://www.buymeacoffee.com/) button.

**Comment by serhiisol** [comment]
@luchillo17 Were you talking about express decorators or socket ?

**Comment by luchillo17** [comment]
@serhiisol Socket.IO ones.

**Comment by serhiisol** [comment]
Yeah, I got it. Fix is on its way :)

**Comment by luchillo17** [comment]
@serhiisol So which one will it be? default global middleware or docs change?

**Comment by serhiisol** [comment]
I'll make middleware optional, which makes more sense to me rather than doc change :D

**Comment by luchillo17** [comment]
Niiiice. 
![Nice Dude](https://render.bitstrips.com/v2/cpanel/2e701e39-8580-47e6-b8fc-476a868fe446-ba7ea600-4a28-4066-8ffb-ca3539b54855-v1.png)

**Comment by serhiisol** [comment]
:) Sorry that It took so long, lots of work, Christmas, New Year .... :)
