### ISSUE TITLE
[Suggestion] allow attaching controllers to a router

### ISSUE THREAD

**Issue by scopsy** [serhiisol/node-decorators#77]
What do you think about adding the ability to attach controllers not only to the app but to Express Router as well? 

This is useful when you want to create a namespace for your controllers, ie:
```
/v1/api
```

we can allow passing a router instance or app instance to the current attachControllers method. Since both use the `.use` method to attach endpoints.
This works just fine so maybe just:
```
const apiRouter = express.Router();
app.use('/v1/api', apiRouter);

attachControllers(apiRouter as any, [
    ...APP_CONTROLLERS
]);
```

**Comment by serhiisol** [comment]
Hi @scopsy, that's a great suggestion, we can just simply modify type of the first argument to accept routers, e.g. `app: Express | Router`.
