### ISSUE TITLE
Async controller handles swallow errors

### ISSUE THREAD

**Issue by scopsy** [serhiisol/node-decorators#82]
Seems like if I create async controller function any thrown error will result in a swallowed exception and won't be caught by the global error middleware unless I explicitly wrap it in try/catch block. 

```
@Controller('/users', [ AuthMiddleware ])
export class UserController {
    @Get('/:id')
    async getUser(@Request() req: Request @Response() res: IAppResponse) {
        throw new Error('Error occurred');

        res.send('Hello World');
    }
}
```

Possible solution would be in `express.ts` file under `routeHandler` function

```
    const handler = controller[methodName].apply(controller, args);

      if (handler instanceof Promise || handler instanceof global.Promise) {
        handler.catch(e => {
          next(e);
        });
      } else {
        return handler;
      }
```

We test for instance of promise and then catch possible errors and pass them to the global error middleware. 

global.Promise used to support user custom promise libraries. 

What do you think ?

**Comment by serhiisol** [comment]
Good catch, I'll tackle that

**Comment by scopsy** [comment]
```
const handler = controller[methodName].apply(controller, args);

   if (handler instanceof Promise || handler instanceof global.Promise) {
      handler.catch(e => {
        next(e);
      });
   }

   return handler;
```

@serhiisol I think it should return handler in any case

**Comment by serhiisol** [comment]
yes, preparing PR with fix, brb :)
