### ISSUE TITLE
Decorators + InversifyJS

### ISSUE THREAD

**Issue by LogansUA** [serhiisol/node-decorators#91]
Hello, I'm trying to use your express decorators with inversifyjs.

The problem that i face off is in `attachControllers` method.

So, I have the service class with registered in intersifyjs container, plus I have controller which looks like this
```typescript
import { Controller, Get } from '@decorators/express';
import { Container } from 'inversify';
...
import { GoogleCloudDataStorageService } from '../services/GoogleCloudDataStorageService';
import { TYPES } from '../types';

declare var app: any;

@Controller('/car')
export class CarController {
    @Get('/:id')
    public async getCarAction(req: RequestInterface, res: ResponseInterface) {
        const googleCloudDataStoreService = (app.get('container') as Container).get<GoogleCloudDataStorageService>(TYPES.GoogleCloudDataStorageService);

        const result = await googleCloudDataStoreService.sayHello();

        return res.status(HttpStatus.OK).json({
            message: result,
        });
    }
}
```
In my `app.ts` file I'm registering controller like this
```typescript
...dependecies
import { attachControllers } from '@decorators/express';
import { CarController } from './controllers/CarController';

...

const apiRouter = express.Router();
attachControllers(app, [CarController]);
```

Then I get the error from inversify container
```
Missing required @injectable annotation in: GoogleCloudDataStorageService.
```

However if I write example route like this
```typescript
app.use('/api/v2', async (req, res) => {
    try {
        const googleCloudDataStoreService = container.get<GoogleCloudDataStorageService>(TYPES.GoogleCloudDataStorageService);
        const result = await googleCloudDataStoreService.sayHello();

        return res.json({ a: result });
    } catch (error) {
        console.error(error);
    }
});
```

And remove attaching controllers function - this route will works normal.

# Solution

After few hours of monkey clicking i found that your `@decorators/express` somehow rewrites the `reflect-metadata` which I'm using for `inversifyjs` and clears the metadata for my classes.

So the solution is to replace importing `reflect-metadata`, on the beginning of the project, with your `@decorators/express`.
Maybe you could add some checking for it? Or maybe there's better solution to do it?

Thank you.

**Comment by LogansUA** [comment]
@serhiisol posted it only for history, so if you'll not going to somehow fix it - you can close it.

**Comment by serhiisol** [comment]
Hi @LogansUA, thanks for your feedback, I can take a look :) but why do you need inversify if decorators have own di container?

**Comment by LogansUA** [comment]
Well, from my point of view, the InversifyJS has much more features that I'm going to use and, no offence, but it has much bigger community.

**Comment by serhiisol** [comment]
Sure, no problems :D I'll take a look later

**Comment by drexlerux** [comment]
`
attachControllerInstances(apiRouter, [aid.container.get('MenuController')]);
`

**Comment by serhiisol** [comment]
👍
