### ISSUE TITLE
Passing injectable from dependency to dependent package

### ISSUE THREAD

**Issue by mingos777** [serhiisol/node-decorators#92]
I have two packages, "core" and "api". Core is api's dependency.

Core exposes an injection token that is meant to be used by the api.

Now, the issue is that since both packages depend on "@decorators/di", npm creates two separate instances of the package - one in node_modules insode api, the other one inside core. Therefore, api's DI container is unable to make use of core's injectables.

Is there a way to make the two "talk" to each other, even a hacky one?

**Comment by serhiisol** [comment]
Hi @mingos777, have you tried `peerDependency` ?

**Comment by mingos777** [comment]
@serhiisol indeed, `peerDependency` did the trick. Thanks for the suggestion.
