### ISSUE TITLE
[Question] How to register response handler?

### ISSUE THREAD

**Issue by kneurgao** [serhiisol/node-decorators#95]
I'm able to register an error handler as follows. It works fine.

```
@Injectable()
class ErrorHandler implements ErrorMiddleware {
    public use(error: Error, request: Request, response: Response, next: NextFunction) {
        console.log('ErrorHandler.use()');
        response.status(500).send(error.message);
    }
}

```

Similarly, is there any provision for injection of response handler to process a response?

It should get invoked with the handler registered using `@Next` in a controller method. All the routes should return through a common response handler.

Thanks in anticipation!

**Comment by serhiisol** [comment]
Hi @kneurgao, I don't really understand your question, could you explain what you really want here ?

**Comment by kneurgao** [comment]
What I want to have is a central point to send response to client instead of writing res.send() in each route handler. It may also include some post processing once the response is out of controller.

Also, could you please explain me the purpose of `@Next` in a route handler of controller.

**Comment by serhiisol** [comment]
Every express route handler behaves like middleware and has access to the next function.
Not really sure I understand your request. `res.send` is like essential part of the route handling as far as I know.

**Comment by kneurgao** [comment]
Yes, I agree that res.send is an essential part of route handling.
However what I wanted to have is that every route handler should not directly return the response. Instead it should call a next() handler which will take care of returning the response to the client using res.send().

The reason of this is to invoke some common behavior before returning any response (like wrapping response, adding few more attributes, etc). To avoid redundancy in each router, I wanted to have a common function which would do this job.

Could you please provide some more information on how does @Next in a route handler of controller work?

**Comment by serhiisol** [comment]
I'm not really sure that your proposed feature is possible to implement, otherwise you can make a PR with this feature.
`@Next` just returns native next function.
In general next function is needed only if you have more than one handler for the same route, otherwise you should invoke `res.send`.

Of course I can make a workaround for this, create two handlers for each route where the second one will send response that somehow previous function returned, but I'm aware of all possible side effects that might happen during all the handlers execution.

**Comment by kneurgao** [comment]
Yes, I understand the constraints associated with this feature.
As of now, I will continue send the response from route handlers until I figure out some better option to achieve this.
Thank you for your time and consideration.

**Comment by serhiisol** [comment]
No Problem:)
