### ISSUE TITLE
decorators notation

### ISSUE THREAD

**Issue by vitalics** [serhiisol/node-decorators#96]
Decorators - function. In JS all function write in lowercase. Why method/parameter/property names decorator is start from capital symbol?
p.s. Class decorators need to start from capital, because class first symbol - capital. Also this notation help other developer to know - what is class decorator and what is method/property/parameter decorator

Example:
``` ts
@Injectable() // capital, because class decorator
class SomeClass{
@someProperty() public readonly myInjection; // start from lowercase, because this is property

@someMethod() // start from lowercase, because this is method
public method(@someParameter() myParameter: any){}  // start from lowercase, because this is parameter
}
````

**Comment by serhiisol** [comment]
It doesn't necessarily follow this pattern. For example all the angular's decorators start with capital case, that's the rule they agreed on. Another example official example from typescriptlang.org http://www.typescriptlang.org/docs/handbook/decorators.html even class decorators start with small letter.

**Comment by serhiisol** [comment]
For now closed, feel free to comment it, we might open this ticket back
